### ISSUE TITLE
Repo mit Composer einbindbar machen

### ISSUE THREAD

**Issue by Fonata** [deezaster/germanphonetic#10]
Dafür braucht es eine Datei `composer.json`. Außerdem muss vermutlich das [Packagist-Formular](https://packagist.org/packages/submit) ausgefüllt werden.

Danke, das würde die Verwendung dieses Repositories vereinfachen.

**Comment by deezaster** [comment]
Da es sich hier lediglich um 2 Implentierungen (SQL und PHP) im Sinne eines Beispielcodes (Snippets) handelt, werde ich von einer Packetierung absehen.

Trotzdem viel Spass mit dem Code...
