### ISSUE TITLE
Problem mit Namen die auf c/k enden können

### ISSUE THREAD

**Issue by Joerg-L** [deezaster/germanphonetic#7]
Hallo,
erstmal vielen Dank für den Code, welcher wirklich gut funktioniert.
Beim testen des Codes sind uns mit Namen, welche sowohl auf c oder k enden können, Probleme aufgefallen.

Yannik -> 064
Yannic -> 068
Dominic -> 2668
Dominik -> 2664

Die Java-Implementierung unter http://lingulist.de/pyjs/demos/kph-demo.html weisst jeweils die gleichen Zahlenwerte als Ergebnis aus.

Haben Sie eine Idee woran das liegt bzw. welche Interpretation korrekt wäre?
Gruß
Jörg Lang

**Comment by deezaster** [comment]
Gemäss Algorithumusbeschreibung (https://de.wikipedia.org/wiki/K%C3%B6lner_Phonetik) ist die Behandlung des Buchstabens C nicht zu 100% definiert. Weil aber andere Implementierungen eine 4 liefern, werde ich dies natürlich auch machen (und ist ja schliesslich logisch, dass Yannic und Yannik phonetisch identisch sind)
